"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const game_1 = require("./game");
const player_1 = require("./player");
const tic_tac_toe_view_manager_1 = require("./tic_tac_toe_view_manager");
let game = new game_1.Game(3, 3);
game.addPlayer(new player_1.Player('John Doe', 'x'));
game.addPlayer(new player_1.Player('Jason Bourne', 'o'));
game.board.print();
console.log(game.status);
game.printSummary();
let resOfMove;
resOfMove = game.nextMove(0, 0);
resOfMove = game.nextMove(0, 0);
resOfMove = game.nextMove(1, 1);
resOfMove = game.nextMove(0, 2);
resOfMove = game.nextMove(2, 2);
resOfMove = game.nextMove(0, 1);
resOfMove = game.nextMove(2, 1);
game.board.print();
game.printSummary();
let canvas = document.getElementById('tic-tac-toe-board');
let resetButton = document.getElementsByClassName('resetButton')[0];
let scorePresenter = document.getElementsByClassName('scoreDiv')[0];
let manager = new tic_tac_toe_view_manager_1.GameViewManager(canvas, 3, (msg) => { alert(msg); }, resetButton, scorePresenter);
manager.initBoard(new player_1.Player('John Doe', 'x'), new player_1.Player('Jason Bourne', 'o'));
manager.nextMove(0, 0);
manager.nextMove(0, 0);
manager.nextMove(1, 1);
manager.nextMove(0, 2);
manager.nextMove(2, 2);
manager.nextMove(0, 1);
manager.nextMove(2, 1);
//# sourceMappingURL=index.js.map